server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://lerk:8761/eureka
    register-with-eureka: false
  instance:
    hostname: eureka
spring:
  application:
    name: eureka
